# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: About
    url: /#about
    weight: 20
  - name: FAQs
    url: /#faqs
    weight: 30
  - name: Hugo Blox Resources
    weight: 40
    hasChildren: true
  - parent: Hugo Blox Resources
    name: Blog Demo
    url: blog/
